[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "onnx>=1.19.0",
    "silero-vad>=6.0.0",
    "speechbrain==1.0.3",
]
